openapi: '3.0.0'
info:
  title: API
  version: 1.0.0
  description: API
servers:
  - url: "http://localhost:8080"
paths:
  /api/me:
    get:
      summary: Get current user
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: uuid
        name:
          type: string
        email:
          type: string